"""Created payment_expired_at

Revision ID: 01adbdc5153f
Revises: 7fc1125e4214
Create Date: 2026-02-03 17:15:31.191271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01adbdc5153f'
down_revision: Union[str, Sequence[str], None] = '7fc1125e4214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('payment_expires_at', sa.DateTime(timezone=True), nullable=True, comment='When patient payment window expires (15 minutes from approval)'))
    op.alter_column('appointments', 'approval_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When doctor approval window expires (24 hours from request)',
               existing_nullable=True)
    op.create_index('idx_payment_expires', 'appointments', ['payment_expires_at', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_payment_expires', table_name='appointments')
    op.alter_column('appointments', 'approval_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When doctor approval window expires (24 hours from request)',
               existing_nullable=True)
    op.drop_column('appointments', 'payment_expires_at')
    # ### end Alembic commands ###
