"""added more tables

Revision ID: 441fd5397928
Revises: 1f0f876f5c50
Create Date: 2026-01-30 12:58:54.772706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '441fd5397928'
down_revision: Union[str, Sequence[str], None] = '1f0f876f5c50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('doctors', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_doctors_speciality'), 'doctors', ['speciality'], unique=False)
    op.add_column('patients', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('patients', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'updated_at')
    op.drop_column('patients', 'created_at')
    op.drop_index(op.f('ix_doctors_speciality'), table_name='doctors')
    op.drop_column('doctors', 'updated_at')
    op.drop_column('doctors', 'created_at')
    # ### end Alembic commands ###
