"""changed status of slot table

Revision ID: 52c35fde7e15
Revises: ccfd5c428a4e
Create Date: 2026-02-02 13:50:37.097032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52c35fde7e15'
down_revision: Union[str, Sequence[str], None] = 'ccfd5c428a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_doctor_date_availability', 'doctor_availability', ['doctor_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_doctor_date_availability', 'doctor_availability', type_='unique')
    # ### end Alembic commands ###
