"""changed patients table - added dob instead of age

Revision ID: 60aa8413088f
Revises: 
Create Date: 2026-01-29 10:26:44.071820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60aa8413088f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('dob', sa.Date(), nullable=False))
    op.drop_column('patients', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('patients', 'dob')
    # ### end Alembic commands ###
