"""added address to doctor model

Revision ID: 6c6be1c0d0b0
Revises: 8626a1485d74
Create Date: 2026-01-29 12:27:24.421582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c6be1c0d0b0'
down_revision: Union[str, Sequence[str], None] = '8626a1485d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('doctors', sa.Column('longitude', sa.Float(), nullable=False))
    op.add_column('doctors', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'address')
    op.drop_column('doctors', 'longitude')
    op.drop_column('doctors', 'latitude')
    # ### end Alembic commands ###
