"""added mappings

Revision ID: 7c0ba1298548
Revises: 6c6be1c0d0b0
Create Date: 2026-01-29 16:48:16.356757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c0ba1298548'
down_revision: Union[str, Sequence[str], None] = '6c6be1c0d0b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('devices_user_id_fkey'), 'devices', type_='foreignkey')
    op.create_foreign_key(None, 'devices', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(op.f('doctors_user_id_fkey'), 'doctors', type_='foreignkey')
    op.create_foreign_key(None, 'doctors', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(op.f('patients_user_id_fkey'), 'patients', type_='foreignkey')
    op.create_foreign_key(None, 'patients', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.drop_constraint(op.f('refresh_tokens_device_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'refresh_tokens', 'devices', ['device_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_device_id_fkey'), 'refresh_tokens', 'devices', ['device_id'], ['id'])
    op.create_foreign_key(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.create_foreign_key(op.f('patients_user_id_fkey'), 'patients', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.create_foreign_key(op.f('doctors_user_id_fkey'), 'doctors', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.create_foreign_key(op.f('devices_user_id_fkey'), 'devices', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
