"""changed appointment table

Revision ID: 7fc1125e4214
Revises: 5ff54198b2b3
Create Date: 2026-02-03 15:08:34.305739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fc1125e4214'
down_revision: Union[str, Sequence[str], None] = '5ff54198b2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('approval_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('idx_approval_expires', 'appointments', ['approval_expires_at', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_approval_expires', table_name='appointments')
    op.drop_column('appointments', 'approval_expires_at')
    # ### end Alembic commands ###
