"""removed unique id on slot

Revision ID: 9101fa3dad84
Revises: 01adbdc5153f
Create Date: 2026-02-04 17:16:20.941816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9101fa3dad84'
down_revision: Union[str, Sequence[str], None] = '01adbdc5153f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('appointments_slot_id_key'), 'appointments', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('appointments_slot_id_key'), 'appointments', ['slot_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
