"""description

Revision ID: afc2652e7bd9
Revises: 52c35fde7e15
Create Date: 2026-02-02 14:05:22.029862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afc2652e7bd9'
down_revision: Union[str, Sequence[str], None] = '52c35fde7e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_slots', sa.Column('held_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('doctor_slots', sa.Column('held_by_patient_id', sa.Integer(), nullable=True))
    op.add_column('doctor_slots', sa.Column('held_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('idx_held_by_patient', 'doctor_slots', ['held_by_patient_id', 'status'], unique=False)
    op.create_index('idx_held_expires', 'doctor_slots', ['held_expires_at'], unique=False, postgresql_where=sa.text("status = 'HELD'"))
    op.create_foreign_key(None, 'doctor_slots', 'users', ['held_by_patient_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doctor_slots', type_='foreignkey')
    op.drop_index('idx_held_expires', table_name='doctor_slots', postgresql_where=sa.text("status = 'HELD'"))
    op.drop_index('idx_held_by_patient', table_name='doctor_slots')
    op.drop_column('doctor_slots', 'held_expires_at')
    op.drop_column('doctor_slots', 'held_by_patient_id')
    op.drop_column('doctor_slots', 'held_at')
    # ### end Alembic commands ###
